"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import { Play, X } from "lucide-react";
import demoVideos from "@/data/demo-videos.json";

type FeatureVideo = {
  slug: string;
  title: string;
  description: string;
  src: string;
};

const FEATURE_VIDEOS = demoVideos.feature_videos as FeatureVideo[];

type Props = {
  title?: string;
  subtitle?: string;
};

export function FeatureVideos({
  title = "See StudyBuddy in action",
  subtitle = "Two short looks at what StudyBuddy does — biology and chemistry, end-to-end.",
}: Props) {
  return (
    <section id="see-it-in-action" className="scroll-mt-20 bg-white px-4 py-20">
      <div className="mx-auto max-w-5xl">
        <div className="text-center">
          <h2 className="text-3xl font-bold text-gray-900 sm:text-4xl">{title}</h2>
          <p className="mt-3 text-lg text-gray-600">{subtitle}</p>
        </div>
        <div className="mt-12 grid grid-cols-1 gap-6 md:grid-cols-2">
          {FEATURE_VIDEOS.map((video) => (
            <FeatureVideoCard key={video.slug} video={video} />
          ))}
        </div>
      </div>
    </section>
  );
}

function FeatureVideoCard({ video }: { video: FeatureVideo }) {
  const dialogRef = useRef<HTMLDialogElement>(null);
  const videoRef = useRef<HTMLVideoElement>(null);
  const [open, setOpen] = useState(false);
  const anchorId = `video-${video.slug}`;
  const matchHash = `#${anchorId}`;

  const handleOpen = useCallback(() => {
    dialogRef.current?.showModal();
    setOpen(true);
    if (videoRef.current) {
      videoRef.current.currentTime = 0;
      videoRef.current.play().catch(() => {
        // autoplay blocked — controls remain visible
      });
    }
  }, []);

  const handleClose = useCallback(() => {
    if (videoRef.current) videoRef.current.pause();
    dialogRef.current?.close();
    setOpen(false);
    // Clear our matching hash so a second click on the same banner button
    // re-fires hashchange (browsers don't refire when the hash is unchanged).
    if (typeof window !== "undefined" && window.location.hash === matchHash) {
      history.replaceState(null, "", window.location.pathname + window.location.search);
    }
  }, [matchHash]);

  // Click on the dialog backdrop (the dialog itself, not its content) closes.
  const handleDialogClick = (e: React.MouseEvent<HTMLDialogElement>) => {
    if (e.target === dialogRef.current) handleClose();
  };

  // Auto-open the modal when the URL hash matches this video — supports the
  // banner "Biology"/"Chemistry" CTAs at the top of the page, and shareable
  // direct links like /#video-chemstory.
  useEffect(() => {
    const checkHash = () => {
      if (window.location.hash === matchHash) {
        // Small delay so the browser's smooth-scroll has time to land before
        // the modal pops over it.
        setTimeout(handleOpen, 150);
      }
    };
    checkHash();
    window.addEventListener("hashchange", checkHash);
    return () => window.removeEventListener("hashchange", checkHash);
  }, [matchHash, handleOpen]);

  return (
    <>
      <button
        id={anchorId}
        type="button"
        onClick={handleOpen}
        aria-label={`Play: ${video.title}`}
        className="group block scroll-mt-24 overflow-hidden rounded-xl border border-gray-200 bg-white text-left shadow-sm transition-all duration-200 hover:border-blue-500 hover:shadow-lg"
      >
        <div className="relative aspect-video overflow-hidden bg-gray-900">
          {/* First-frame preview via native <video preload="metadata">. Acts as
              the thumbnail until/unless a poster JPEG is generated by ffmpeg. */}
          <video
            src={video.src}
            preload="metadata"
            muted
            playsInline
            className="h-full w-full object-cover"
            aria-hidden="true"
          />
          <div className="absolute inset-0 flex items-center justify-center bg-black/30 transition group-hover:bg-black/40">
            <div className="flex h-16 w-16 items-center justify-center rounded-full bg-white/95 shadow-xl transition-transform group-hover:scale-110">
              <Play className="ml-1 h-8 w-8 fill-blue-600 text-blue-600" />
            </div>
          </div>
        </div>
        <div className="p-5">
          <h3 className="text-lg font-semibold text-gray-900 transition-colors group-hover:text-blue-600">
            {video.title}
          </h3>
          <p className="mt-1.5 text-sm leading-relaxed text-gray-500">
            {video.description}
          </p>
        </div>
      </button>

      <dialog
        ref={dialogRef}
        onClick={handleDialogClick}
        onCancel={handleClose}
        className="m-0 w-full max-w-4xl rounded-xl bg-black p-0 backdrop:bg-black/80 backdrop:backdrop-blur-sm"
      >
        <div className="relative">
          <button
            type="button"
            onClick={handleClose}
            aria-label="Close video"
            className="absolute top-2 right-2 z-10 flex h-10 w-10 items-center justify-center rounded-full bg-black/60 text-white transition hover:bg-black/80"
          >
            <X className="h-5 w-5" />
          </button>
          <video
            ref={videoRef}
            src={video.src}
            controls
            playsInline
            preload="metadata"
            className="aspect-video w-full bg-black"
          >
            Your browser doesn&apos;t support HTML5 video.{" "}
            <a href={video.src}>Download {video.title}</a> instead.
          </video>
        </div>
      </dialog>

      {/* `open` state is referenced for future a11y enhancements
          (focus trapping, scroll lock); intentionally a no-op for now. */}
      <span className="sr-only">{open ? "Video open" : ""}</span>
    </>
  );
}
