#!/usr/bin/env bash
# =============================================================================
# StudyBuddy OnDemand — Dev Start Script
#
# Usage:
#   ./dev_start.sh              — start all services + API
#   ./dev_start.sh test         — run the automated test suite only
#   ./dev_start.sh stop         — stop background containers
#   ./dev_start.sh reset        — stop containers AND delete volumes (fresh DB)
#
# Requires: Python 3.11+, podman OR docker
# Auth0 credentials must be in .env (see SETUP REQUIRED section below)
# =============================================================================

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BACKEND_DIR="$REPO_ROOT/backend"
ENV_FILE="$REPO_ROOT/.env"
VENV_DIR="$REPO_ROOT/venv"

# Container names
DB_CONTAINER="sb-db"
REDIS_CONTAINER="sb-redis"
TEST_DB_CONTAINER="sb-test-db"
DB_PORT=5432
REDIS_PORT=6379
TEST_DB_PORT=5433   # dedicated test port — never conflicts with dev DB

# ── Colours ───────────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; BLUE='\033[0;34m'; NC='\033[0m'
info()    { echo -e "${BLUE}[INFO]${NC}  $*"; }
success() { echo -e "${GREEN}[OK]${NC}    $*"; }
warn()    { echo -e "${YELLOW}[WARN]${NC}  $*"; }
error()   { echo -e "${RED}[ERROR]${NC} $*" >&2; }

# ── Container runtime detection ───────────────────────────────────────────────
detect_runtime() {
    if command -v podman &>/dev/null; then
        echo "podman"
    elif command -v docker &>/dev/null; then
        echo "docker"
    else
        error "Neither podman nor docker found. Install one and retry."
        exit 1
    fi
}
RUNTIME="$(detect_runtime)"
info "Container runtime: $RUNTIME"

# ── Helpers ───────────────────────────────────────────────────────────────────
gen_secret() {
    python3 -c "import secrets; print(secrets.token_urlsafe(40))"
}

wait_for_port() {
    local host="$1" port="$2" label="$3" timeout=30
    info "Waiting for $label on $host:$port ..."
    for i in $(seq 1 $timeout); do
        if python3 -c "import socket; s=socket.create_connection(('$host', $port), timeout=1)" 2>/dev/null; then
            success "$label is ready"
            return 0
        fi
        sleep 1
    done
    error "$label did not become ready after ${timeout}s"
    exit 1
}

# ── .env bootstrap ────────────────────────────────────────────────────────────
bootstrap_env() {
    if [[ -f "$ENV_FILE" ]]; then
        info ".env already exists — skipping generation"
        return
    fi

    info "Generating $ENV_FILE with random secrets ..."

    POSTGRES_PASSWORD="$(gen_secret)"
    REDIS_PASSWORD="$(gen_secret)"
    JWT_SECRET="$(gen_secret)"
    ADMIN_JWT_SECRET="$(gen_secret)"
    METRICS_TOKEN="$(gen_secret)"

    cat > "$ENV_FILE" <<EOF
# ============================================================
# StudyBuddy OnDemand — Environment Configuration
# Generated by dev_start.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# ============================================================

# ── Application ──────────────────────────────────────────────
APP_ENV=development
APP_VERSION=0.1.0
LOG_LEVEL=INFO

# ── Database ─────────────────────────────────────────────────
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
DATABASE_URL=postgresql://studybuddy:${POSTGRES_PASSWORD}@localhost:${DB_PORT}/studybuddy

# ── Redis ────────────────────────────────────────────────────
REDIS_PASSWORD=${REDIS_PASSWORD}
REDIS_URL=redis://:${REDIS_PASSWORD}@localhost:${REDIS_PORT}/0

# ── JWT secrets (must be ≥32 chars and different) ────────────
JWT_SECRET=${JWT_SECRET}
ADMIN_JWT_SECRET=${ADMIN_JWT_SECRET}

# ── Observability ────────────────────────────────────────────
METRICS_TOKEN=${METRICS_TOKEN}

# ── CORS ─────────────────────────────────────────────────────
ALLOWED_ORIGINS=http://localhost:3000,http://localhost:8080

# ── Content store (local filesystem for dev) ─────────────────
CONTENT_STORE_PATH=${REPO_ROOT}/data/content_store

# ── Celery (uses Redis by default) ───────────────────────────
# CELERY_BROKER_URL=   # leave blank to reuse REDIS_URL

# ────────────────────────────────────────────────────────────
# SETUP REQUIRED — fill in your Auth0 tenant details below
# ────────────────────────────────────────────────────────────
# 1. Sign up at https://auth0.com (free tier is fine for dev)
# 2. Create a Regular Web Application for students  → AUTH0_STUDENT_CLIENT_ID
# 3. Create a Regular Web Application for teachers  → AUTH0_TEACHER_CLIENT_ID
# 4. Create a Machine-to-Machine application,
#    authorise it against the Auth0 Management API with scopes:
#      read:users  update:users  delete:users
#    → AUTH0_MGMT_CLIENT_ID + AUTH0_MGMT_CLIENT_SECRET
# 5. Note your tenant domain                        → AUTH0_DOMAIN
# ────────────────────────────────────────────────────────────
AUTH0_DOMAIN=YOUR_TENANT.us.auth0.com
AUTH0_JWKS_URL=https://YOUR_TENANT.us.auth0.com/.well-known/jwks.json
AUTH0_STUDENT_CLIENT_ID=REPLACE_ME
AUTH0_TEACHER_CLIENT_ID=REPLACE_ME
AUTH0_MGMT_API_URL=https://YOUR_TENANT.us.auth0.com/api/v2
AUTH0_MGMT_CLIENT_ID=REPLACE_ME
AUTH0_MGMT_CLIENT_SECRET=REPLACE_ME

# ── Sentry (optional — leave blank to disable) ───────────────
SENTRY_DSN=
EOF

    success ".env created at $ENV_FILE"
    warn "Auth0 fields are placeholders. Edit .env and fill in your tenant before testing student/teacher login."
}

# ── Source .env into shell ────────────────────────────────────────────────────
load_env() {
    # Export non-comment, non-empty lines.
    # Values with spaces (e.g. Gmail App Passwords) must be quoted in .env:
    #   SMTP_PASSWORD='xxxx xxxx xxxx xxxx'
    # Single- and double-quoted assignments are valid bash and sourced correctly.
    set -o allexport
    # shellcheck disable=SC1090
    source <(grep -E '^[A-Z_]+=.' "$ENV_FILE")
    set +o allexport
}

# ── Python virtualenv ────────────────────────────────────────────────────────
setup_venv() {
    if [[ ! -d "$VENV_DIR" ]]; then
        info "Creating Python virtualenv at $VENV_DIR ..."
        python3 -m venv "$VENV_DIR"
    fi
    # shellcheck disable=SC1091
    source "$VENV_DIR/bin/activate"
    if ! python -c "import fastapi" 2>/dev/null; then
        info "Installing Python dependencies ..."
        pip install -q -r "$BACKEND_DIR/requirements.txt"
    fi
    success "Virtualenv ready"
}

# ── Port conflict detection ───────────────────────────────────────────────────
# Returns the container name using a given port, or empty string if none.
container_on_port() {
    local port="$1"
    $RUNTIME ps --format "{{.Names}} {{.Ports}}" 2>/dev/null \
        | grep ":${port}->" \
        | awk '{print $1}' \
        | head -1
}

# ── Start PostgreSQL ──────────────────────────────────────────────────────────
start_postgres() {
    # Already our container and running?
    if $RUNTIME inspect "$DB_CONTAINER" --format "{{.State.Running}}" 2>/dev/null | grep -q "true"; then
        success "PostgreSQL already running ($DB_CONTAINER)"
        return
    fi

    # Our container exists but is stopped/created — remove stale instance first.
    if $RUNTIME inspect "$DB_CONTAINER" &>/dev/null; then
        info "Removing stale $DB_CONTAINER container ..."
        $RUNTIME rm -f "$DB_CONTAINER" &>/dev/null || true
    fi

    # Check if another container already holds the port.
    local occupant
    occupant="$(container_on_port "$DB_PORT")"
    if [[ -n "$occupant" ]]; then
        warn "Port $DB_PORT is in use by container '$occupant'."
        warn "Stopping and removing it to free the port ..."
        $RUNTIME stop  "$occupant" &>/dev/null || true
        $RUNTIME rm -f "$occupant" &>/dev/null || true
        sleep 1
    fi

    info "Starting PostgreSQL container ..."
    $RUNTIME run -d \
        --name "$DB_CONTAINER" \
        -e POSTGRES_DB=studybuddy \
        -e POSTGRES_USER=studybuddy \
        -e POSTGRES_PASSWORD="${POSTGRES_PASSWORD}" \
        -p "${DB_PORT}:5432" \
        -v sb_postgres_data:/var/lib/postgresql/data \
        docker.io/postgres:16-alpine \
        postgres -c log_min_messages=WARNING

    wait_for_port localhost "$DB_PORT" "PostgreSQL"
    sleep 2
}

# ── Start Redis ───────────────────────────────────────────────────────────────
start_redis() {
    # Already our container and running?
    if $RUNTIME inspect "$REDIS_CONTAINER" --format "{{.State.Running}}" 2>/dev/null | grep -q "true"; then
        success "Redis already running ($REDIS_CONTAINER)"
        return
    fi

    # Our container exists but is stopped/created — remove stale instance first.
    if $RUNTIME inspect "$REDIS_CONTAINER" &>/dev/null; then
        info "Removing stale $REDIS_CONTAINER container ..."
        $RUNTIME rm -f "$REDIS_CONTAINER" &>/dev/null || true
    fi

    # Check if another container already holds the port.
    local occupant
    occupant="$(container_on_port "$REDIS_PORT")"
    if [[ -n "$occupant" ]]; then
        warn "Port $REDIS_PORT is in use by container '$occupant'."
        warn "Stopping and removing it to free the port ..."
        $RUNTIME stop  "$occupant" &>/dev/null || true
        $RUNTIME rm -f "$occupant" &>/dev/null || true
        sleep 1
    fi

    info "Starting Redis container ..."
    $RUNTIME run -d \
        --name "$REDIS_CONTAINER" \
        -p "${REDIS_PORT}:6379" \
        -v sb_redis_data:/data \
        docker.io/redis:7-alpine \
        redis-server \
            --requirepass "${REDIS_PASSWORD}" \
            --appendonly yes \
            --appendfsync everysec \
            --maxmemory 256mb \
            --maxmemory-policy allkeys-lru

    wait_for_port localhost "$REDIS_PORT" "Redis"
}

# ── Run Alembic migrations ────────────────────────────────────────────────────
run_migrations() {
    info "Running Alembic migrations ..."
    pushd "$BACKEND_DIR" > /dev/null
    alembic upgrade head
    popd > /dev/null
    success "Migrations applied"
}

# ── Start API server ──────────────────────────────────────────────────────────
start_api() {
    info "Starting FastAPI development server on http://localhost:8000 ..."
    echo ""
    echo -e "  ${GREEN}API docs:${NC}  http://localhost:8000/api/docs"
    echo -e "  ${GREEN}Health:${NC}    http://localhost:8000/health"
    echo -e "  ${GREEN}Metrics:${NC}   http://localhost:8000/metrics  (token-protected)"
    echo ""
    pushd "$BACKEND_DIR" > /dev/null
    PYTHONPATH=. uvicorn main:app --reload --host 0.0.0.0 --port 8000
    popd > /dev/null
}

# ── Start test-only PostgreSQL (fixed testpassword, studybuddy_test DB) ────────
start_test_db() {
    if $RUNTIME inspect "$TEST_DB_CONTAINER" --format "{{.State.Running}}" 2>/dev/null | grep -q "true"; then
        success "Test PostgreSQL already running ($TEST_DB_CONTAINER)"
        return
    fi

    if $RUNTIME inspect "$TEST_DB_CONTAINER" &>/dev/null; then
        $RUNTIME rm -f "$TEST_DB_CONTAINER" &>/dev/null || true
    fi

    local occupant
    occupant="$(container_on_port "$TEST_DB_PORT")"
    if [[ -n "$occupant" ]]; then
        warn "Port $TEST_DB_PORT in use by '$occupant' — removing it ..."
        $RUNTIME stop "$occupant" &>/dev/null || true
        $RUNTIME rm -f "$occupant" &>/dev/null || true
        sleep 1
    fi

    info "Starting test PostgreSQL on port $TEST_DB_PORT ..."
    $RUNTIME run -d \
        --name "$TEST_DB_CONTAINER" \
        -e POSTGRES_DB=studybuddy_test \
        -e POSTGRES_USER=studybuddy \
        -e POSTGRES_PASSWORD=testpassword \
        -p "${TEST_DB_PORT}:5432" \
        docker.io/postgres:16-alpine \
        postgres -c log_min_messages=WARNING

    wait_for_port localhost "$TEST_DB_PORT" "Test PostgreSQL"
    sleep 2
}

# ── Run tests ─────────────────────────────────────────────────────────────────
run_tests() {
    start_test_db
    info "Running test suite ..."
    pushd "$BACKEND_DIR" > /dev/null
    # Clear any production env vars exported by load_env() so conftest.py's
    # os.environ.setdefault() picks up its own isolated test values.
    unset JWT_SECRET ADMIN_JWT_SECRET METRICS_TOKEN \
          DATABASE_URL REDIS_URL POSTGRES_PASSWORD REDIS_PASSWORD \
          AUTH0_DOMAIN AUTH0_JWKS_URL AUTH0_STUDENT_CLIENT_ID \
          AUTH0_TEACHER_CLIENT_ID AUTH0_MGMT_CLIENT_ID \
          AUTH0_MGMT_CLIENT_SECRET AUTH0_MGMT_API_URL
    # Point tests at the dedicated test DB (different port, same host/creds as conftest expects).
    export DATABASE_URL="postgresql://studybuddy:testpassword@localhost:${TEST_DB_PORT}/studybuddy_test"
    PYTHONPATH=. pytest tests/ -v
    popd > /dev/null
}

# ── Stop containers ───────────────────────────────────────────────────────────
stop_containers() {
    info "Stopping containers ..."
    $RUNTIME stop "$DB_CONTAINER"      2>/dev/null || true
    $RUNTIME stop "$REDIS_CONTAINER"   2>/dev/null || true
    $RUNTIME stop "$TEST_DB_CONTAINER" 2>/dev/null || true
    success "Containers stopped"
}

# ── Reset (stop + delete volumes) ────────────────────────────────────────────
# By default, preserves ./content_store_data/ (AI-generated lessons — expensive
# to regenerate, cost real LLM tokens). Pass --wipe-content to also delete them.
reset_all() {
    local wipe_content="${1:-}"
    local content_dir="${SCRIPT_DIR:-$(pwd)}/content_store_data"
    local lesson_count=0
    if [[ -d "$content_dir" ]]; then
        lesson_count=$(find "$content_dir" -name "meta.json" 2>/dev/null | wc -l)
    fi

    warn "This will DELETE all database data and Redis state."
    if [[ "$wipe_content" == "--wipe-content" ]]; then
        warn "You also passed --wipe-content: ${lesson_count} built lessons in ${content_dir} will be DELETED."
    else
        info "Content store preserved: ${lesson_count} built lessons in ${content_dir}."
        info "Use './dev_start.sh reset --wipe-content' to also delete them."
    fi
    read -r -p "Are you sure? [y/N] " confirm
    [[ "$confirm" =~ ^[Yy]$ ]] || { info "Aborted."; exit 0; }

    stop_containers
    $RUNTIME rm -f "$DB_CONTAINER"      2>/dev/null || true
    $RUNTIME rm -f "$REDIS_CONTAINER"   2>/dev/null || true
    $RUNTIME rm -f "$TEST_DB_CONTAINER" 2>/dev/null || true
    $RUNTIME volume rm sb_postgres_data sb_redis_data 2>/dev/null || true

    if [[ "$wipe_content" == "--wipe-content" ]] && [[ -d "$content_dir" ]]; then
        rm -rf "$content_dir"
        success "Content store wiped (${lesson_count} lessons deleted)."
    fi

    success "Containers and volumes removed. Run ./dev_start.sh to start fresh."
}

# ── Main ─────────────────────────────────────────────────────────────────────
COMMAND="${1:-start}"

case "$COMMAND" in
  start)
    bootstrap_env
    load_env
    setup_venv
    start_postgres
    start_redis
    run_migrations
    start_api
    ;;

  test)
    bootstrap_env
    load_env
    setup_venv
    run_tests
    ;;

  stop)
    stop_containers
    ;;

  reset)
    reset_all "${2:-}"
    ;;

  *)
    echo "Usage: $0 [start|test|stop|reset [--wipe-content]]"
    exit 1
    ;;
esac
