"""How long a unit should take a student, estimated from the lesson itself.

The student dashboard's "Up next" card carried `"estimated_minutes": 20` as a
literal, so every unit told every student "about 20 minutes" regardless of
whether the lesson ran to 200 words or 3,000. A tester asked what pattern the
card followed; this is half the answer (the other half — what unit comes next —
was #733).

## Why not the pipeline's own number

Lessons already carry `estimated_duration_minutes`, generated by the LLM, and it
is present on 250 of the 253 real lesson files in the content store. It is not
the number this card wants: measured across those files it takes exactly three
values — 45 (201 lessons), 40 (41), 50 (8). That is a class-period estimate,
"how long to TEACH this", and it does not vary with the lesson.

A student reading a 205-word lesson does not need 45 minutes, and telling them
so is the same defect as telling them 20.

## Why not measured time

`lesson_views.duration_s` records how long students actually spent, which would
beat any model. It is NULL for every row: `end_lesson_view()` exists and writes
it, but nothing calls it, so `avg_lesson_duration_s` on the demo is None across
15 lesson views. Filed separately — when that data exists, it should replace
this estimate rather than sit beside it.

## What this does

Counts the words a student actually reads — synopsis, learning objectives, key
points, and every section heading and body — and divides by a reading rate scaled
to their grade, plus a flat allowance for the quiz.

Counting ALL of those fields, not just section bodies, matters: 90 of the 253
real lessons predate the Epic 11 C-5 regeneration and carry only a `synopsis`
(pitfall #33). Counting section bodies alone would return nothing for a third of
the corpus. Counting everything leaves 3 lessons below the floor.
"""

from __future__ import annotations

# Silent-reading rates, words per minute, at the ends of the supported range.
# Grade 5 is deliberately conservative: Content Rule #3 targets lesson prose one
# to two grades BELOW the student's own, so the reader is by design not being
# stretched, and an estimate that runs short is the one that erodes trust.
_WPM_GRADE_5 = 130
_WPM_GRADE_12 = 220

# Flat, and honest about being flat. The quiz is 8 questions and this is not
# measured — `progress_answers.ms_taken` is collected and could replace it, but
# it is per-question and per-attempt, so turning it into a per-unit figure is its
# own piece of work rather than a constant to swap.
_QUIZ_ALLOWANCE_MIN = 5

# Below this the lesson is a stub, not a lesson, and any number would be noise.
# Returning None lets the card omit the line rather than print something wrong.
_MIN_WORDS = 20


def _wpm_for_grade(grade: int | None) -> int:
    """Linear between the grade 5 and grade 12 rates, clamped to that range."""
    if grade is None:
        # Mid-range rather than a guess at either end.
        grade = 8
    g = max(5, min(12, int(grade)))
    span = _WPM_GRADE_12 - _WPM_GRADE_5
    return round(_WPM_GRADE_5 + span * (g - 5) / 7)


def count_lesson_words(lesson: dict) -> int:
    """Words a student reads on the lesson page.

    Tolerant of all three lesson shapes `_normalize_lesson` handles (pitfall
    #33): old-format, new rich with `sections`, and legacy-minimal with only a
    `synopsis`. A missing key contributes nothing rather than raising — this
    runs on the dashboard path, where a malformed lesson must cost its own
    estimate and nothing else.
    """
    if not isinstance(lesson, dict):
        return 0

    parts: list[str] = [str(lesson.get("synopsis") or "")]

    for key in ("key_points", "learning_objectives"):
        value = lesson.get(key)
        if isinstance(value, list):
            parts.extend(str(v) for v in value)
        elif value:
            parts.append(str(value))

    sections = lesson.get("sections")
    if isinstance(sections, list):
        for section in sections:
            if not isinstance(section, dict):
                continue
            parts.append(str(section.get("heading") or ""))
            parts.append(str(section.get("body") or ""))

    return len(" ".join(parts).split())


def estimate_unit_minutes(lesson: dict, grade: int | None) -> int | None:
    """Minutes to read the lesson and sit the quiz, or None if unknowable.

    Rounded to the nearest 5: the card says "about", and a card reading "about
    17 minutes" claims a precision this does not have.
    """
    words = count_lesson_words(lesson)
    if words < _MIN_WORDS:
        return None

    minutes = words / _wpm_for_grade(grade) + _QUIZ_ALLOWANCE_MIN
    return max(5, round(minutes / 5) * 5)
