import { BotMessageSquare } from "lucide-react";

/**
 * EU AI Act Article 13 — Transparency obligation.
 *
 * Any AI system that generates or manipulates content must inform users
 * that the content has been artificially generated or manipulated.
 * This component satisfies that obligation for every lesson, quiz,
 * tutorial, and experiment page.
 *
 * Rendered as a static Server Component — no interactivity needed.
 */
export function AIContentDisclosure() {
  return (
    <p className="mt-6 flex items-center gap-1.5 text-xs text-gray-400">
      <BotMessageSquare
        className="h-3.5 w-3.5 shrink-0 text-gray-300"
        aria-hidden="true"
      />
      <span>
        This content was generated by AI using the StudyBuddy content pipeline.
        It has been reviewed for accuracy and age-appropriateness before
        publication.{" "}
        <a
          href="/about#Content"
          className="underline underline-offset-2 hover:text-gray-600"
        >
          Learn more
        </a>
        .
      </span>
    </p>
  );
}
