"use client";

/**
 * HelpWidget — floating contextual help button + slide-up response panel.
 *
 * Renders a fixed violet circle button in the bottom-right corner of every
 * school portal page. Clicking it opens a compact panel that lets the user
 * type a question and receive a step-by-step answer generated by the
 * Deliver-1 RAG pipeline (POST /api/v1/help/ask).
 *
 * Role is auto-detected from the `sb_teacher_token` JWT in localStorage so
 * the answer is always persona-appropriate (school_admin vs teacher).
 * Page context is captured via usePathname() for improved retrieval.
 *
 * Deliver-3: account_state context signals are collected before each ask —
 * first_login from the JWT, and setup-status counts from the API (school_admin
 * only). Collection is best-effort: a failed fetch never blocks the help call.
 */

import { useState, useRef, useEffect, KeyboardEvent } from "react";
import { usePathname } from "next/navigation";
import {
  HelpCircle,
  X,
  Send,
  ChevronRight,
  Loader2,
  AlertCircle,
} from "lucide-react";
import { askHelp, type HelpAskResponse, type AccountState, HELP_BASE_URL } from "@/lib/api/help";

// ── JWT helpers ───────────────────────────────────────────────────────────────

interface JwtPayload {
  role?: string;
  school_id?: string;
  first_login?: boolean;
}

function readJwtPayload(): JwtPayload {
  if (typeof window === "undefined") return {};
  try {
    const token = localStorage.getItem("sb_teacher_token");
    if (!token) return {};
    return JSON.parse(
      atob(token.split(".")[1].replace(/-/g, "+").replace(/_/g, "/")),
    ) as JwtPayload;
  } catch {
    return {};
  }
}

function readRoleFromJwt(): "school_admin" | "teacher" {
  const payload = readJwtPayload();
  return payload.role === "school_admin" ? "school_admin" : "teacher";
}

// ── Account state collection (Deliver-3) ─────────────────────────────────────

/**
 * Collect context signals to pass as account_state in the help request.
 *
 * - first_login: from JWT (always available if token exists)
 * - setup counts: from GET /schools/{id}/setup-status (school_admin only)
 *
 * Best-effort: any failure silently returns what has been collected so far.
 */
async function collectAccountState(
  role: "school_admin" | "teacher",
): Promise<AccountState | undefined> {
  const payload = readJwtPayload();
  const state: AccountState = {};

  if (payload.first_login === true) {
    state.first_login = true;
  }

  if (role === "school_admin" && payload.school_id) {
    try {
      const token = localStorage.getItem("sb_teacher_token");
      const res = await fetch(
        `${HELP_BASE_URL}/schools/${payload.school_id}/setup-status`,
        { headers: token ? { Authorization: `Bearer ${token}` } : {} },
      );
      if (res.ok) {
        const status = await res.json();
        state.teacher_count = status.teacher_count ?? 0;
        state.student_count = status.student_count ?? 0;
        state.classroom_count = status.classroom_count ?? 0;
        state.curriculum_assigned = status.curriculum_assigned ?? false;
      }
    } catch {
      // best-effort — never block the help request
    }
  }

  return Object.keys(state).length > 0 ? state : undefined;
}

// ── Sub-components ────────────────────────────────────────────────────────────

function StepList({ steps }: { steps: string[] }) {
  return (
    <ol className="space-y-2">
      {steps.map((step, i) => (
        <li key={i} className="flex gap-2.5">
          <span className="mt-0.5 flex h-5 w-5 shrink-0 items-center justify-center rounded-full bg-violet-100 text-xs font-semibold text-violet-700">
            {i + 1}
          </span>
          <span className="text-sm text-gray-700 leading-snug">{step}</span>
        </li>
      ))}
    </ol>
  );
}

function RelatedChips({ related }: { related: string[] }) {
  if (related.length === 0) return null;
  return (
    <div className="flex flex-wrap gap-1.5 pt-1">
      {related.map((r) => (
        <span
          key={r}
          className="inline-flex items-center gap-1 rounded-full border border-violet-200 bg-violet-50 px-2.5 py-0.5 text-xs text-violet-700"
        >
          <ChevronRight className="h-3 w-3" />
          {r}
        </span>
      ))}
    </div>
  );
}

function ResponseCard({ response }: { response: HelpAskResponse }) {
  return (
    <div className="space-y-3">
      {/* Title */}
      <p className="text-sm font-semibold text-gray-900">{response.title}</p>

      {/* Steps */}
      <StepList steps={response.steps} />

      {/* Result */}
      {response.result && (
        <p className="rounded-md bg-green-50 px-3 py-2 text-xs text-green-800 leading-snug">
          {response.result}
        </p>
      )}

      {/* Related topics */}
      <RelatedChips related={response.related} />

      {/* Sources (small attribution) */}
      {response.sources.length > 0 && (
        <p className="text-xs text-gray-400">
          Sources: {response.sources.join(" · ")}
        </p>
      )}
    </div>
  );
}

function LoadingSkeleton() {
  return (
    <div className="space-y-3 animate-pulse">
      <div className="h-4 w-3/4 rounded bg-gray-200" />
      <div className="space-y-2">
        {[1, 2, 3].map((i) => (
          <div key={i} className="flex gap-2.5">
            <div className="mt-0.5 h-5 w-5 shrink-0 rounded-full bg-gray-200" />
            <div className="h-4 flex-1 rounded bg-gray-200" />
          </div>
        ))}
      </div>
      <div className="h-8 rounded bg-gray-200" />
    </div>
  );
}

// ── Main widget ───────────────────────────────────────────────────────────────

export function HelpWidget() {
  const pathname = usePathname();
  const [isOpen, setIsOpen] = useState(false);
  const [question, setQuestion] = useState("");
  const [isLoading, setIsLoading] = useState(false);
  const [response, setResponse] = useState<HelpAskResponse | null>(null);
  const [error, setError] = useState<string | null>(null);
  const textareaRef = useRef<HTMLTextAreaElement>(null);

  // Focus textarea when panel opens.
  useEffect(() => {
    if (isOpen) {
      setTimeout(() => textareaRef.current?.focus(), 50);
    }
  }, [isOpen]);

  function handleOpen() {
    setIsOpen(true);
  }

  function handleClose() {
    setIsOpen(false);
    // Keep question + response for when they re-open.
  }

  function handleReset() {
    setQuestion("");
    setResponse(null);
    setError(null);
    setTimeout(() => textareaRef.current?.focus(), 50);
  }

  async function handleSubmit() {
    const q = question.trim();
    if (q.length < 3 || isLoading) return;

    setIsLoading(true);
    setError(null);
    setResponse(null);

    try {
      const role = readRoleFromJwt();
      // Collect context signals in parallel with the loading state — best-effort.
      const account_state = await collectAccountState(role);
      const data = await askHelp({ question: q, page: pathname, role, account_state });
      setResponse(data);
    } catch (err) {
      setError(
        err instanceof Error
          ? err.message
          : "Something went wrong. Please try again.",
      );
    } finally {
      setIsLoading(false);
    }
  }

  function handleKeyDown(e: KeyboardEvent<HTMLTextAreaElement>) {
    // Ctrl/Cmd + Enter submits.
    if ((e.ctrlKey || e.metaKey) && e.key === "Enter") {
      e.preventDefault();
      handleSubmit();
    }
  }

  const canSubmit = question.trim().length >= 3 && !isLoading;

  return (
    <>
      {/* ── Floating trigger button ──────────────────────────────────────── */}
      {!isOpen && (
        <button
          onClick={handleOpen}
          aria-label="Open help"
          className="fixed bottom-6 right-6 z-50 flex h-12 w-12 items-center justify-center rounded-full bg-violet-600 text-white shadow-lg transition-transform hover:scale-105 hover:bg-violet-700 focus:outline-none focus:ring-2 focus:ring-violet-500 focus:ring-offset-2"
        >
          <HelpCircle className="h-6 w-6" />
        </button>
      )}

      {/* ── Slide-up panel ──────────────────────────────────────────────── */}
      {isOpen && (
        <div
          className="fixed bottom-6 right-6 z-50 flex w-[360px] flex-col rounded-2xl bg-white shadow-2xl ring-1 ring-gray-200"
          style={{ maxHeight: "calc(100vh - 80px)" }}
          role="dialog"
          aria-label="StudyBuddy Help"
          aria-modal="false"
        >
          {/* Header */}
          <div className="flex items-center justify-between rounded-t-2xl bg-violet-600 px-4 py-3">
            <div className="flex items-center gap-2">
              <HelpCircle className="h-4 w-4 text-violet-200" />
              <span className="text-sm font-semibold text-white">
                StudyBuddy Help
              </span>
            </div>
            <button
              onClick={handleClose}
              aria-label="Close help"
              className="rounded p-0.5 text-violet-200 hover:bg-violet-700 hover:text-white focus:outline-none"
            >
              <X className="h-4 w-4" />
            </button>
          </div>

          {/* Scrollable body */}
          <div className="flex flex-1 flex-col gap-3 overflow-y-auto p-4">
            {/* Question input */}
            <div>
              <label
                htmlFor="help-question"
                className="mb-1.5 block text-xs font-medium text-gray-600"
              >
                What do you need help with?
              </label>
              <textarea
                id="help-question"
                ref={textareaRef}
                value={question}
                onChange={(e) => setQuestion(e.target.value)}
                onKeyDown={handleKeyDown}
                placeholder="e.g. How do I add a teacher?"
                rows={2}
                className="w-full resize-none rounded-lg border border-gray-300 px-3 py-2 text-sm text-gray-900 placeholder-gray-400 focus:border-violet-500 focus:outline-none focus:ring-1 focus:ring-violet-500"
              />
              <p className="mt-1 text-right text-xs text-gray-400">
                Ctrl+Enter to send
              </p>
            </div>

            {/* Submit / Reset buttons */}
            <div className="flex gap-2">
              <button
                onClick={handleSubmit}
                disabled={!canSubmit}
                className="flex flex-1 items-center justify-center gap-1.5 rounded-lg bg-violet-600 px-3 py-2 text-sm font-medium text-white transition-colors hover:bg-violet-700 disabled:cursor-not-allowed disabled:opacity-50"
              >
                {isLoading ? (
                  <Loader2 className="h-4 w-4 animate-spin" />
                ) : (
                  <Send className="h-4 w-4" />
                )}
                {isLoading ? "Thinking…" : "Ask"}
              </button>
              {(response || error) && (
                <button
                  onClick={handleReset}
                  className="rounded-lg border border-gray-200 px-3 py-2 text-sm text-gray-600 hover:bg-gray-50"
                >
                  New question
                </button>
              )}
            </div>

            {/* Loading skeleton */}
            {isLoading && <LoadingSkeleton />}

            {/* Error state */}
            {error && !isLoading && (
              <div className="flex items-start gap-2 rounded-lg bg-red-50 p-3">
                <AlertCircle className="mt-0.5 h-4 w-4 shrink-0 text-red-500" />
                <p className="text-sm text-red-700">{error}</p>
              </div>
            )}

            {/* Response */}
            {response && !isLoading && <ResponseCard response={response} />}
          </div>
        </div>
      )}
    </>
  );
}
