#!/usr/bin/env bun
/**
 * Generate the 30 visual-library sidecars for the existing exemplar SVGs in
 * G11-MATH-001 + G11-PHYS-002 (issue #322 phase 2).
 *
 * Run from repo root:
 *   bun scripts/seed_library_sidecars.ts
 *
 * Idempotent: re-running overwrites the sidecars from this declarative
 * spec, so this is also the canonical edit surface — change the spec
 * here, re-run, and re-commit.
 *
 * After this writes, validate with:
 *   bun scripts/validate_library_metadata.ts \
 *     "sample_content/**\/Option2_Catalogue/**\/*.metadata.yaml"
 */

import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { mkdirSync } from "node:fs";

type Kind = "image" | "image-grid" | "animated-svg" | "video";

interface SidecarSpec {
  asset: string;          // path relative to repo root
  id: string;             // globally unique slug
  kind: Kind;
  subject: "physics" | "chemistry" | "math" | "biology";
  topic_phrase: string;
  keywords: string[];
  source_unit: string;
}

const REPO_ROOT = join(import.meta.dir, "..");

const SPECS: SidecarSpec[] = [
  // ── G11-MATH-001 Sets and Functions ──────────────────────────────────────
  // animations/
  {
    asset: "sample_content/g11-science/G11-MATH-001_Sets_and_Functions/Option2_Catalogue/animations/projectile-smil.svg",
    id: "math-projectile-smil-anim",
    kind: "animated-svg",
    subject: "math",
    topic_phrase: "projectile motion animation",
    keywords: ["projectile", "parabola", "smil", "animated", "motion"],
    source_unit: "G11-MATH-001",
  },
  // arrow-diagrams/
  {
    asset: "sample_content/g11-science/G11-MATH-001_Sets_and_Functions/Option2_Catalogue/arrow-diagrams/bijective.svg",
    id: "math-arrow-diagram-bijective",
    kind: "image",
    subject: "math",
    topic_phrase: "bijective function arrow diagram",
    keywords: ["function", "bijective", "one-to-one", "onto", "arrow-diagram"],
    source_unit: "G11-MATH-001",
  },
  {
    asset: "sample_content/g11-science/G11-MATH-001_Sets_and_Functions/Option2_Catalogue/arrow-diagrams/injective-only.svg",
    id: "math-arrow-diagram-injective-only",
    kind: "image",
    subject: "math",
    topic_phrase: "injective only function arrow diagram",
    keywords: ["function", "injective", "one-to-one", "arrow-diagram"],
    source_unit: "G11-MATH-001",
  },
  {
    asset: "sample_content/g11-science/G11-MATH-001_Sets_and_Functions/Option2_Catalogue/arrow-diagrams/surjective-only.svg",
    id: "math-arrow-diagram-surjective-only",
    kind: "image",
    subject: "math",
    topic_phrase: "surjective only function arrow diagram",
    keywords: ["function", "surjective", "onto", "arrow-diagram"],
    source_unit: "G11-MATH-001",
  },
  {
    asset: "sample_content/g11-science/G11-MATH-001_Sets_and_Functions/Option2_Catalogue/arrow-diagrams/R1-function.svg",
    id: "math-arrow-diagram-r1-function",
    kind: "image",
    subject: "math",
    topic_phrase: "R1 valid function arrow diagram",
    keywords: ["function", "definition", "valid", "arrow-diagram"],
    source_unit: "G11-MATH-001",
  },
  {
    asset: "sample_content/g11-science/G11-MATH-001_Sets_and_Functions/Option2_Catalogue/arrow-diagrams/R2-not-function.svg",
    id: "math-arrow-diagram-r2-not-function",
    kind: "image",
    subject: "math",
    topic_phrase: "R2 not a function arrow diagram",
    keywords: ["function", "counter-example", "uniqueness", "arrow-diagram"],
    source_unit: "G11-MATH-001",
  },
  {
    asset: "sample_content/g11-science/G11-MATH-001_Sets_and_Functions/Option2_Catalogue/arrow-diagrams/R3-function-not-injective.svg",
    id: "math-arrow-diagram-r3-function-not-injective",
    kind: "image",
    subject: "math",
    topic_phrase: "R3 function but not injective",
    keywords: ["function", "not-injective", "many-to-one", "arrow-diagram"],
    source_unit: "G11-MATH-001",
  },
  {
    asset: "sample_content/g11-science/G11-MATH-001_Sets_and_Functions/Option2_Catalogue/arrow-diagrams/R4-not-function.svg",
    id: "math-arrow-diagram-r4-not-function",
    kind: "image",
    subject: "math",
    topic_phrase: "R4 not a function (totality violated)",
    keywords: ["function", "counter-example", "totality", "arrow-diagram"],
    source_unit: "G11-MATH-001",
  },
  // composition/
  {
    asset: "sample_content/g11-science/G11-MATH-001_Sets_and_Functions/Option2_Catalogue/composition/f-after-g.svg",
    id: "math-function-composition-f-after-g",
    kind: "image",
    subject: "math",
    topic_phrase: "function composition f after g pipeline",
    keywords: ["function", "composition", "pipeline", "f-of-g"],
    source_unit: "G11-MATH-001",
  },
  {
    asset: "sample_content/g11-science/G11-MATH-001_Sets_and_Functions/Option2_Catalogue/composition/g-after-f.svg",
    id: "math-function-composition-g-after-f",
    kind: "image",
    subject: "math",
    topic_phrase: "function composition g after f pipeline",
    keywords: ["function", "composition", "pipeline", "g-of-f"],
    source_unit: "G11-MATH-001",
  },
  // power-set/
  {
    asset: "sample_content/g11-science/G11-MATH-001_Sets_and_Functions/Option2_Catalogue/power-set/hasse-3-element.svg",
    id: "math-power-set-hasse-3-element",
    kind: "image",
    subject: "math",
    topic_phrase: "power set Hasse diagram three-element set",
    keywords: ["power-set", "hasse-diagram", "lattice", "subset", "ordering"],
    source_unit: "G11-MATH-001",
  },
  // set-operations/
  {
    asset: "sample_content/g11-science/G11-MATH-001_Sets_and_Functions/Option2_Catalogue/set-operations/union.svg",
    id: "math-set-operation-union-venn",
    kind: "image",
    subject: "math",
    topic_phrase: "set union Venn diagram",
    keywords: ["set-theory", "venn-diagram", "union", "or"],
    source_unit: "G11-MATH-001",
  },
  {
    asset: "sample_content/g11-science/G11-MATH-001_Sets_and_Functions/Option2_Catalogue/set-operations/intersection.svg",
    id: "math-set-operation-intersection-venn",
    kind: "image",
    subject: "math",
    topic_phrase: "set intersection Venn diagram",
    keywords: ["set-theory", "venn-diagram", "intersection", "and"],
    source_unit: "G11-MATH-001",
  },
  {
    asset: "sample_content/g11-science/G11-MATH-001_Sets_and_Functions/Option2_Catalogue/set-operations/difference.svg",
    id: "math-set-operation-difference-venn",
    kind: "image",
    subject: "math",
    topic_phrase: "set difference Venn diagram",
    keywords: ["set-theory", "venn-diagram", "difference", "minus"],
    source_unit: "G11-MATH-001",
  },
  {
    asset: "sample_content/g11-science/G11-MATH-001_Sets_and_Functions/Option2_Catalogue/set-operations/complement.svg",
    id: "math-set-operation-complement-venn",
    kind: "image",
    subject: "math",
    topic_phrase: "set complement Venn diagram",
    keywords: ["set-theory", "venn-diagram", "complement", "universe"],
    source_unit: "G11-MATH-001",
  },

  // ── G11-PHYS-002 Kinematics ─────────────────────────────────────────────
  // section-1-fundamentals/
  {
    asset: "sample_content/g11-science/G11-PHYS-002_Kinematics/Option2_Catalogue/section-1-fundamentals/1d-position-and-displacement.svg",
    id: "physics-kinematics-1d-position-and-displacement",
    kind: "image",
    subject: "physics",
    topic_phrase: "one-dimensional position and displacement on a number line",
    keywords: ["kinematics", "position", "displacement", "1d", "number-line"],
    source_unit: "G11-PHYS-002",
  },
  {
    asset: "sample_content/g11-science/G11-PHYS-002_Kinematics/Option2_Catalogue/section-1-fundamentals/distance-vs-displacement.svg",
    id: "physics-kinematics-distance-vs-displacement",
    kind: "image",
    subject: "physics",
    topic_phrase: "distance versus displacement on a curved path",
    keywords: ["kinematics", "distance", "displacement", "scalar", "vector", "path"],
    source_unit: "G11-PHYS-002",
  },
  {
    asset: "sample_content/g11-science/G11-PHYS-002_Kinematics/Option2_Catalogue/section-1-fundamentals/average-vs-instantaneous-velocity.svg",
    id: "physics-kinematics-average-vs-instantaneous-velocity",
    kind: "image",
    subject: "physics",
    topic_phrase: "average versus instantaneous velocity on x-t curve",
    keywords: ["kinematics", "velocity", "average", "instantaneous", "secant", "tangent"],
    source_unit: "G11-PHYS-002",
  },
  // section-2-uam/
  {
    asset: "sample_content/g11-science/G11-PHYS-002_Kinematics/Option2_Catalogue/section-2-uam/xt-uam.svg",
    id: "physics-kinematics-xt-uam",
    kind: "image",
    subject: "physics",
    topic_phrase: "position-time parabola for uniformly accelerated motion",
    keywords: ["kinematics", "uam", "position-time", "parabola", "x-t-graph"],
    source_unit: "G11-PHYS-002",
  },
  {
    asset: "sample_content/g11-science/G11-PHYS-002_Kinematics/Option2_Catalogue/section-2-uam/vt-uam.svg",
    id: "physics-kinematics-vt-uam",
    kind: "image",
    subject: "physics",
    topic_phrase: "velocity-time line for uniformly accelerated motion",
    keywords: ["kinematics", "uam", "velocity-time", "linear", "v-t-graph"],
    source_unit: "G11-PHYS-002",
  },
  {
    asset: "sample_content/g11-science/G11-PHYS-002_Kinematics/Option2_Catalogue/section-2-uam/at-uam.svg",
    id: "physics-kinematics-at-uam",
    kind: "image",
    subject: "physics",
    topic_phrase: "acceleration-time constant for uniformly accelerated motion",
    keywords: ["kinematics", "uam", "acceleration-time", "constant", "a-t-graph"],
    source_unit: "G11-PHYS-002",
  },
  // section-3-freefall/
  {
    asset: "sample_content/g11-science/G11-PHYS-002_Kinematics/Option2_Catalogue/section-3-freefall/height-vs-time.svg",
    id: "physics-kinematics-freefall-height-vs-time",
    kind: "image",
    subject: "physics",
    topic_phrase: "height versus time for object thrown straight up",
    keywords: ["kinematics", "free-fall", "height", "parabola", "thrown-up"],
    source_unit: "G11-PHYS-002",
  },
  {
    asset: "sample_content/g11-science/G11-PHYS-002_Kinematics/Option2_Catalogue/section-3-freefall/velocity-vs-time.svg",
    id: "physics-kinematics-freefall-velocity-vs-time",
    kind: "image",
    subject: "physics",
    topic_phrase: "velocity versus time for free fall (zero crossing at peak)",
    keywords: ["kinematics", "free-fall", "velocity", "zero-crossing", "direction-reversal"],
    source_unit: "G11-PHYS-002",
  },
  // section-4-projectile/
  {
    asset: "sample_content/g11-science/G11-PHYS-002_Kinematics/Option2_Catalogue/section-4-projectile/trajectory.svg",
    id: "physics-kinematics-projectile-trajectory",
    kind: "image",
    subject: "physics",
    topic_phrase: "projectile motion trajectory at 60 degrees",
    keywords: ["kinematics", "projectile", "trajectory", "parabola", "range", "max-height"],
    source_unit: "G11-PHYS-002",
  },
  {
    asset: "sample_content/g11-science/G11-PHYS-002_Kinematics/Option2_Catalogue/section-4-projectile/velocity-decomposition.svg",
    id: "physics-kinematics-velocity-decomposition",
    kind: "image",
    subject: "physics",
    topic_phrase: "initial velocity decomposition into horizontal and vertical components",
    keywords: ["kinematics", "vector", "decomposition", "horizontal", "vertical", "cos", "sin"],
    source_unit: "G11-PHYS-002",
  },
  {
    asset: "sample_content/g11-science/G11-PHYS-002_Kinematics/Option2_Catalogue/section-4-projectile/key-results.svg",
    id: "physics-kinematics-projectile-key-results",
    kind: "image",
    subject: "physics",
    topic_phrase: "projectile motion key results time of flight range max height",
    keywords: ["kinematics", "projectile", "time-of-flight", "range", "max-height", "formulas"],
    source_unit: "G11-PHYS-002",
  },
  // section-5-graphs/
  {
    asset: "sample_content/g11-science/G11-PHYS-002_Kinematics/Option2_Catalogue/section-5-graphs/xt-with-tangent.svg",
    id: "physics-kinematics-xt-with-tangent",
    kind: "image",
    subject: "physics",
    topic_phrase: "x-t curve with tangent showing instantaneous velocity",
    keywords: ["kinematics", "x-t-graph", "tangent", "slope", "instantaneous-velocity"],
    source_unit: "G11-PHYS-002",
  },
  {
    asset: "sample_content/g11-science/G11-PHYS-002_Kinematics/Option2_Catalogue/section-5-graphs/vt-with-area.svg",
    id: "physics-kinematics-vt-with-area",
    kind: "image",
    subject: "physics",
    topic_phrase: "v-t curve with shaded area showing displacement",
    keywords: ["kinematics", "v-t-graph", "area-under-curve", "displacement", "integration"],
    source_unit: "G11-PHYS-002",
  },
  {
    asset: "sample_content/g11-science/G11-PHYS-002_Kinematics/Option2_Catalogue/section-5-graphs/xt-vt-at-trio.svg",
    id: "physics-kinematics-xt-vt-at-trio",
    kind: "image",
    subject: "physics",
    topic_phrase: "x-t v-t a-t graphs side-by-side for UAM",
    keywords: ["kinematics", "uam", "trio", "side-by-side", "relationships"],
    source_unit: "G11-PHYS-002",
  },
  {
    asset: "sample_content/g11-science/G11-PHYS-002_Kinematics/Option2_Catalogue/section-5-graphs/slope-area-summary.svg",
    id: "physics-kinematics-slope-area-summary",
    kind: "image",
    subject: "physics",
    topic_phrase: "slope and area chain summary x v a",
    keywords: ["kinematics", "slope", "area", "calculus", "differentiation", "integration"],
    source_unit: "G11-PHYS-002",
  },

  // ── G11-PHYS-010 Oscillations and Waves (issue #327) ───────────────────────
  {
    asset: "sample_content/g11-science/G11-PHYS-010_Oscillations_and_Waves/Option2_Catalogue/section-1-shm-kinematics/shm-displacement-time.svg",
    id: "physics-shm-displacement-time",
    kind: "image",
    subject: "physics",
    topic_phrase: "simple harmonic motion displacement vs time",
    keywords: ["shm", "oscillation", "sine-wave", "amplitude", "period", "displacement"],
    source_unit: "G11-PHYS-010",
  },
  {
    asset: "sample_content/g11-science/G11-PHYS-010_Oscillations_and_Waves/Option2_Catalogue/section-1-shm-kinematics/shm-y-v-a-comparison.svg",
    id: "physics-shm-displacement-velocity-acceleration-phase",
    kind: "image",
    subject: "physics",
    topic_phrase: "shm displacement velocity acceleration 90 degree phase",
    keywords: ["shm", "phase", "velocity", "acceleration", "sinusoidal", "comparison"],
    source_unit: "G11-PHYS-010",
  },
  {
    asset: "sample_content/g11-science/G11-PHYS-010_Oscillations_and_Waves/Option2_Catalogue/section-2-energy-pendulum/shm-energy-vs-displacement.svg",
    id: "physics-shm-energy-vs-displacement",
    kind: "image",
    subject: "physics",
    topic_phrase: "shm energy kinetic potential vs displacement",
    keywords: ["shm", "energy", "kinetic", "potential", "conservation", "parabola"],
    source_unit: "G11-PHYS-010",
  },
  {
    asset: "sample_content/g11-science/G11-PHYS-010_Oscillations_and_Waves/Option2_Catalogue/section-2-energy-pendulum/simple-pendulum-restoring-force.svg",
    id: "physics-simple-pendulum-restoring-force",
    kind: "image",
    subject: "physics",
    topic_phrase: "simple pendulum restoring force tangential component",
    keywords: ["pendulum", "restoring-force", "gravity", "tension", "free-body", "tangential"],
    source_unit: "G11-PHYS-010",
  },
  {
    asset: "sample_content/g11-science/G11-PHYS-010_Oscillations_and_Waves/Option2_Catalogue/section-3-wave-properties/transverse-vs-longitudinal.svg",
    id: "physics-transverse-vs-longitudinal-waves",
    kind: "image",
    subject: "physics",
    topic_phrase: "transverse vs longitudinal wave comparison",
    keywords: ["wave", "transverse", "longitudinal", "comparison", "compression", "rarefaction"],
    source_unit: "G11-PHYS-010",
  },
  {
    asset: "sample_content/g11-science/G11-PHYS-010_Oscillations_and_Waves/Option2_Catalogue/section-3-wave-properties/wave-anatomy.svg",
    id: "physics-wave-anatomy-amplitude-wavelength-period",
    kind: "image",
    subject: "physics",
    topic_phrase: "wave anatomy amplitude wavelength crest trough",
    keywords: ["wave", "anatomy", "wavelength", "amplitude", "crest", "trough", "period"],
    source_unit: "G11-PHYS-010",
  },
  {
    asset: "sample_content/g11-science/G11-PHYS-010_Oscillations_and_Waves/Option2_Catalogue/section-4-superposition/superposition-constructive.svg",
    id: "physics-wave-superposition-constructive",
    kind: "image",
    subject: "physics",
    topic_phrase: "wave superposition constructive interference in phase",
    keywords: ["superposition", "constructive", "interference", "in-phase", "amplitude-doubles"],
    source_unit: "G11-PHYS-010",
  },
  {
    asset: "sample_content/g11-science/G11-PHYS-010_Oscillations_and_Waves/Option2_Catalogue/section-4-superposition/superposition-destructive.svg",
    id: "physics-wave-superposition-destructive",
    kind: "image",
    subject: "physics",
    topic_phrase: "wave superposition destructive interference 180 phase",
    keywords: ["superposition", "destructive", "interference", "out-of-phase", "cancellation"],
    source_unit: "G11-PHYS-010",
  },
  {
    asset: "sample_content/g11-science/G11-PHYS-010_Oscillations_and_Waves/Option2_Catalogue/section-4-superposition/standing-wave-modes.svg",
    id: "physics-standing-wave-modes-string",
    kind: "image",
    subject: "physics",
    topic_phrase: "standing wave modes harmonics string both ends fixed",
    keywords: ["standing-wave", "harmonic", "fundamental", "node", "antinode", "string"],
    source_unit: "G11-PHYS-010",
  },
  {
    asset: "sample_content/g11-science/G11-PHYS-010_Oscillations_and_Waves/Option2_Catalogue/section-5-damping-doppler/damped-oscillation-comparison.svg",
    id: "physics-damped-oscillation-regimes-comparison",
    kind: "image",
    subject: "physics",
    topic_phrase: "damped oscillation under critical over damping comparison",
    keywords: ["damped", "under-damped", "critical", "over-damped", "decay", "envelope"],
    source_unit: "G11-PHYS-010",
  },
  {
    asset: "sample_content/g11-science/G11-PHYS-010_Oscillations_and_Waves/Option2_Catalogue/section-5-damping-doppler/resonance-amplitude-curve.svg",
    id: "physics-resonance-amplitude-vs-driving-frequency",
    kind: "image",
    subject: "physics",
    topic_phrase: "resonance amplitude vs driving frequency damping",
    keywords: ["resonance", "driving-frequency", "natural-frequency", "amplitude", "damping", "peak"],
    source_unit: "G11-PHYS-010",
  },
  {
    asset: "sample_content/g11-science/G11-PHYS-010_Oscillations_and_Waves/Option2_Catalogue/section-5-damping-doppler/doppler-source-approaching.svg",
    id: "physics-doppler-effect-moving-source",
    kind: "image",
    subject: "physics",
    topic_phrase: "doppler effect moving source compressed wavefronts",
    keywords: ["doppler", "moving-source", "wavefront", "frequency-shift", "approaching", "pitch"],
    source_unit: "G11-PHYS-010",
  },

  // ── G9-SCI-001 Kinematics 1D (issue #328) ──────────────────────────────────
  {
    asset: "sample_content/g9-stem/G9-SCI-001_Kinematics_1D/Option2_Catalogue/section-1-fundamentals/1d-position-and-displacement.svg",
    id: "physics-g9-1d-position-on-number-line",
    kind: "image",
    subject: "physics",
    topic_phrase: "1d position number line origin signed coordinate",
    keywords: ["position", "number-line", "origin", "1d", "coordinate", "g9-kinematics"],
    source_unit: "G9-SCI-001",
  },
  {
    asset: "sample_content/g9-stem/G9-SCI-001_Kinematics_1D/Option2_Catalogue/section-1-fundamentals/distance-vs-displacement.svg",
    id: "physics-g9-distance-vs-displacement",
    kind: "image",
    subject: "physics",
    topic_phrase: "distance walked versus straight-line displacement",
    keywords: ["distance", "displacement", "path", "scalar-vs-vector", "g9-kinematics"],
    source_unit: "G9-SCI-001",
  },
  {
    asset: "sample_content/g9-stem/G9-SCI-001_Kinematics_1D/Option2_Catalogue/section-1-fundamentals/average-vs-instantaneous-speed.svg",
    id: "physics-g9-average-vs-instantaneous-speed",
    kind: "image",
    subject: "physics",
    topic_phrase: "average speed versus instantaneous speedometer reading",
    keywords: ["average-speed", "instantaneous-speed", "speedometer", "trip", "g9-kinematics"],
    source_unit: "G9-SCI-001",
  },
  {
    asset: "sample_content/g9-stem/G9-SCI-001_Kinematics_1D/Option2_Catalogue/section-2-uniform-motion/motion-strip-uniform.svg",
    id: "physics-g9-motion-strip-uniform",
    kind: "image",
    subject: "physics",
    topic_phrase: "stroboscopic motion strip uniform constant speed equal spacing",
    keywords: ["motion-strip", "stroboscope", "uniform", "constant-speed", "equal-spacing", "g9-kinematics"],
    source_unit: "G9-SCI-001",
  },
  {
    asset: "sample_content/g9-stem/G9-SCI-001_Kinematics_1D/Option2_Catalogue/section-2-uniform-motion/xt-uniform.svg",
    id: "physics-g9-distance-vs-time-uniform",
    kind: "image",
    subject: "physics",
    topic_phrase: "distance vs time straight line uniform motion slope speed",
    keywords: ["distance-time", "uniform", "linear", "slope", "constant-speed", "g9-kinematics"],
    source_unit: "G9-SCI-001",
  },
  {
    asset: "sample_content/g9-stem/G9-SCI-001_Kinematics_1D/Option2_Catalogue/section-2-uniform-motion/vt-uniform.svg",
    id: "physics-g9-speed-vs-time-uniform",
    kind: "image",
    subject: "physics",
    topic_phrase: "speed vs time horizontal line uniform motion area distance",
    keywords: ["speed-time", "uniform", "horizontal-line", "area-under-curve", "distance", "g9-kinematics"],
    source_unit: "G9-SCI-001",
  },
  {
    asset: "sample_content/g9-stem/G9-SCI-001_Kinematics_1D/Option2_Catalogue/section-3-accelerated-motion/motion-strip-accelerated.svg",
    id: "physics-g9-motion-strip-accelerated",
    kind: "image",
    subject: "physics",
    topic_phrase: "stroboscopic motion strip accelerated growing spacing",
    keywords: ["motion-strip", "stroboscope", "accelerated", "growing-spacing", "uniform-acceleration", "g9-kinematics"],
    source_unit: "G9-SCI-001",
  },
  {
    asset: "sample_content/g9-stem/G9-SCI-001_Kinematics_1D/Option2_Catalogue/section-3-accelerated-motion/xt-accelerated.svg",
    id: "physics-g9-distance-vs-time-accelerated",
    kind: "image",
    subject: "physics",
    topic_phrase: "distance vs time parabola accelerated motion increasing slope",
    keywords: ["distance-time", "accelerated", "parabola", "increasing-slope", "g9-kinematics"],
    source_unit: "G9-SCI-001",
  },
  {
    asset: "sample_content/g9-stem/G9-SCI-001_Kinematics_1D/Option2_Catalogue/section-3-accelerated-motion/vt-accelerated.svg",
    id: "physics-g9-speed-vs-time-accelerated",
    kind: "image",
    subject: "physics",
    topic_phrase: "speed vs time straight rising line uniform acceleration",
    keywords: ["speed-time", "accelerated", "linear-rise", "uniform-acceleration", "slope", "g9-kinematics"],
    source_unit: "G9-SCI-001",
  },
  {
    asset: "sample_content/g9-stem/G9-SCI-001_Kinematics_1D/Option2_Catalogue/section-3-accelerated-motion/uniform-vs-accelerated-comparison.svg",
    id: "physics-g9-uniform-vs-accelerated-comparison",
    kind: "image-grid",
    subject: "physics",
    topic_phrase: "uniform versus accelerated motion side by side d-t and v-t plots",
    keywords: ["uniform", "accelerated", "comparison", "d-t", "v-t", "side-by-side", "g9-kinematics"],
    source_unit: "G9-SCI-001",
  },

  // ── G11-CHEM-002 Structure of Atom (issue #329) ────────────────────────────
  {
    asset: "sample_content/g11-science/G11-CHEM-002_Structure_of_Atom/Option2_Catalogue/section-1-discovery/cathode-ray-experiment.svg",
    id: "chemistry-cathode-ray-experiment",
    kind: "image",
    subject: "chemistry",
    topic_phrase: "thomson cathode ray tube experiment electron discovery",
    keywords: ["thomson", "cathode-ray", "electron", "discovery", "deflection"],
    source_unit: "G11-CHEM-002",
  },
  {
    asset: "sample_content/g11-science/G11-CHEM-002_Structure_of_Atom/Option2_Catalogue/section-1-discovery/rutherford-gold-foil.svg",
    id: "chemistry-rutherford-gold-foil",
    kind: "image",
    subject: "chemistry",
    topic_phrase: "rutherford gold foil alpha scattering nucleus discovery",
    keywords: ["rutherford", "alpha-particle", "gold-foil", "nucleus", "scattering"],
    source_unit: "G11-CHEM-002",
  },
  {
    asset: "sample_content/g11-science/G11-CHEM-002_Structure_of_Atom/Option2_Catalogue/section-1-discovery/subatomic-particles-comparison.svg",
    id: "chemistry-subatomic-particles-comparison",
    kind: "image",
    subject: "chemistry",
    topic_phrase: "subatomic particles proton neutron electron charge mass comparison",
    keywords: ["proton", "neutron", "electron", "subatomic", "comparison", "charge", "mass"],
    source_unit: "G11-CHEM-002",
  },
  {
    asset: "sample_content/g11-science/G11-CHEM-002_Structure_of_Atom/Option2_Catalogue/section-2-atomic-models/thomson-plum-pudding.svg",
    id: "chemistry-thomson-plum-pudding-model",
    kind: "image",
    subject: "chemistry",
    topic_phrase: "thomson plum pudding atomic model diffuse positive sphere embedded electrons",
    keywords: ["thomson", "plum-pudding", "atomic-model", "historical-model", "embedded"],
    source_unit: "G11-CHEM-002",
  },
  {
    asset: "sample_content/g11-science/G11-CHEM-002_Structure_of_Atom/Option2_Catalogue/section-2-atomic-models/rutherford-nuclear-model.svg",
    id: "chemistry-rutherford-nuclear-model",
    kind: "image",
    subject: "chemistry",
    topic_phrase: "rutherford nuclear planetary atomic model dense nucleus orbiting electrons",
    keywords: ["rutherford", "nuclear-model", "planetary", "historical-model", "orbits"],
    source_unit: "G11-CHEM-002",
  },
  {
    asset: "sample_content/g11-science/G11-CHEM-002_Structure_of_Atom/Option2_Catalogue/section-2-atomic-models/bohr-shell-model.svg",
    id: "chemistry-bohr-shell-model",
    kind: "image",
    subject: "chemistry",
    topic_phrase: "bohr quantized shells K L M energy levels electron occupancy",
    keywords: ["bohr", "shell-model", "quantized", "k-l-m", "energy-levels"],
    source_unit: "G11-CHEM-002",
  },
  {
    asset: "sample_content/g11-science/G11-CHEM-002_Structure_of_Atom/Option2_Catalogue/section-3-orbitals/s-orbital.svg",
    id: "chemistry-s-orbital-spherical",
    kind: "image",
    subject: "chemistry",
    topic_phrase: "s orbital spherical electron cloud isotropic probability",
    keywords: ["s-orbital", "spherical", "orbital-shape", "l-zero", "isotropic"],
    source_unit: "G11-CHEM-002",
  },
  {
    asset: "sample_content/g11-science/G11-CHEM-002_Structure_of_Atom/Option2_Catalogue/section-3-orbitals/p-orbitals.svg",
    id: "chemistry-p-orbitals-three-dumbbells",
    kind: "image",
    subject: "chemistry",
    topic_phrase: "p orbital three perpendicular dumbbells px py pz",
    keywords: ["p-orbital", "dumbbell", "px-py-pz", "orbital-shape", "l-one"],
    source_unit: "G11-CHEM-002",
  },
  {
    asset: "sample_content/g11-science/G11-CHEM-002_Structure_of_Atom/Option2_Catalogue/section-3-orbitals/d-orbitals.svg",
    id: "chemistry-d-orbitals-five-shapes",
    kind: "image",
    subject: "chemistry",
    topic_phrase: "d orbital five shapes cloverleaf and dumbbell with doughnut",
    keywords: ["d-orbital", "cloverleaf", "orbital-shape", "l-two", "five-orbitals"],
    source_unit: "G11-CHEM-002",
  },
  {
    asset: "sample_content/g11-science/G11-CHEM-002_Structure_of_Atom/Option2_Catalogue/section-3-orbitals/quantum-numbers-tree.svg",
    id: "chemistry-quantum-numbers-n-l-ml-ms",
    kind: "image",
    subject: "chemistry",
    topic_phrase: "four quantum numbers n l m_l m_s electron addressing system",
    keywords: ["quantum-numbers", "principal", "azimuthal", "magnetic", "spin", "pauli"],
    source_unit: "G11-CHEM-002",
  },
  {
    asset: "sample_content/g11-science/G11-CHEM-002_Structure_of_Atom/Option2_Catalogue/section-4-electron-config-spectra/aufbau-diagonal-rule.svg",
    id: "chemistry-aufbau-diagonal-filling-order",
    kind: "image",
    subject: "chemistry",
    topic_phrase: "aufbau principle diagonal filling order orbital sequence",
    keywords: ["aufbau", "filling-order", "diagonal-rule", "electron-configuration", "madelung"],
    source_unit: "G11-CHEM-002",
  },
  {
    asset: "sample_content/g11-science/G11-CHEM-002_Structure_of_Atom/Option2_Catalogue/section-4-electron-config-spectra/hydrogen-emission-spectrum.svg",
    id: "chemistry-hydrogen-emission-spectrum-balmer",
    kind: "image",
    subject: "chemistry",
    topic_phrase: "hydrogen emission spectrum balmer series visible lines wavelength",
    keywords: ["hydrogen", "emission-spectrum", "balmer", "h-alpha", "h-beta", "line-spectrum", "wavelength"],
    source_unit: "G11-CHEM-002",
  },
  {
    asset: "sample_content/g11-science/G11-CHEM-002_Structure_of_Atom/Option2_Catalogue/section-4-electron-config-spectra/orbital-diagram-nitrogen-hund.svg",
    id: "chemistry-orbital-diagram-nitrogen-hund",
    kind: "image",
    subject: "chemistry",
    topic_phrase: "nitrogen orbital diagram hund rule parallel spins 2p three unpaired",
    keywords: ["nitrogen", "orbital-diagram", "hund-rule", "pauli", "parallel-spins", "unpaired"],
    source_unit: "G11-CHEM-002",
  },

  // ── G6-SCI-001 Cells (issue #330) ──────────────────────────────────────────
  {
    asset: "sample_content/g6-stem/G6-SCI-001_Cells/Option2_Catalogue/section-1-whole-cells/animal-cell-labeled.svg",
    id: "biology-animal-cell-labeled",
    kind: "image",
    subject: "biology",
    topic_phrase: "labeled animal cell major organelles nucleus mitochondria er golgi",
    keywords: ["animal-cell", "labeled", "organelle", "nucleus", "mitochondria", "g6-cells"],
    source_unit: "G6-SCI-001",
  },
  {
    asset: "sample_content/g6-stem/G6-SCI-001_Cells/Option2_Catalogue/section-1-whole-cells/plant-cell-labeled.svg",
    id: "biology-plant-cell-labeled",
    kind: "image",
    subject: "biology",
    topic_phrase: "labeled plant cell cell wall chloroplast vacuole organelles",
    keywords: ["plant-cell", "labeled", "cell-wall", "chloroplast", "vacuole", "g6-cells"],
    source_unit: "G6-SCI-001",
  },
  {
    asset: "sample_content/g6-stem/G6-SCI-001_Cells/Option2_Catalogue/section-1-whole-cells/animal-vs-plant-comparison.svg",
    id: "biology-animal-vs-plant-comparison",
    kind: "image",
    subject: "biology",
    topic_phrase: "animal versus plant cell side by side comparison differences",
    keywords: ["animal-cell", "plant-cell", "comparison", "differences", "side-by-side", "g6-cells"],
    source_unit: "G6-SCI-001",
  },
  {
    asset: "sample_content/g6-stem/G6-SCI-001_Cells/Option2_Catalogue/section-2-organelles/nucleus-anatomy.svg",
    id: "biology-nucleus-anatomy",
    kind: "image",
    subject: "biology",
    topic_phrase: "nucleus anatomy nuclear envelope nucleolus chromatin pores",
    keywords: ["nucleus", "nuclear-envelope", "nucleolus", "chromatin", "nuclear-pore", "g6-cells"],
    source_unit: "G6-SCI-001",
  },
  {
    asset: "sample_content/g6-stem/G6-SCI-001_Cells/Option2_Catalogue/section-2-organelles/mitochondrion-anatomy.svg",
    id: "biology-mitochondrion-anatomy",
    kind: "image",
    subject: "biology",
    topic_phrase: "mitochondrion bean shape cristae matrix powerhouse atp",
    keywords: ["mitochondrion", "cristae", "matrix", "atp", "powerhouse", "g6-cells"],
    source_unit: "G6-SCI-001",
  },
  {
    asset: "sample_content/g6-stem/G6-SCI-001_Cells/Option2_Catalogue/section-2-organelles/chloroplast-anatomy.svg",
    id: "biology-chloroplast-anatomy",
    kind: "image",
    subject: "biology",
    topic_phrase: "chloroplast lens shape thylakoid grana stroma photosynthesis",
    keywords: ["chloroplast", "thylakoid", "grana", "stroma", "photosynthesis", "g6-cells"],
    source_unit: "G6-SCI-001",
  },
  {
    asset: "sample_content/g6-stem/G6-SCI-001_Cells/Option2_Catalogue/section-2-organelles/cell-membrane-bilayer.svg",
    id: "biology-cell-membrane-phospholipid-bilayer",
    kind: "image",
    subject: "biology",
    topic_phrase: "cell membrane phospholipid bilayer hydrophilic head hydrophobic tail",
    keywords: ["cell-membrane", "phospholipid", "bilayer", "head-tail", "protein-channel", "g6-cells"],
    source_unit: "G6-SCI-001",
  },
  {
    asset: "sample_content/g6-stem/G6-SCI-001_Cells/Option2_Catalogue/section-2-organelles/endoplasmic-reticulum-and-golgi.svg",
    id: "biology-endoplasmic-reticulum-and-golgi",
    kind: "image",
    subject: "biology",
    topic_phrase: "rough endoplasmic reticulum golgi apparatus protein pipeline ribosomes vesicles",
    keywords: ["rough-er", "golgi", "ribosome", "protein-pipeline", "vesicle", "g6-cells"],
    source_unit: "G6-SCI-001",
  },
  {
    asset: "sample_content/g6-stem/G6-SCI-001_Cells/Option2_Catalogue/section-3-scale-microscopy/cell-size-scale.svg",
    id: "biology-cell-size-scale-chart",
    kind: "image",
    subject: "biology",
    topic_phrase: "cell size scale virus bacterium animal plant log scale microscopy",
    keywords: ["cell-size", "scale", "log-scale", "virus", "bacterium", "microscopy", "g6-cells"],
    source_unit: "G6-SCI-001",
  },
  {
    asset: "sample_content/g6-stem/G6-SCI-001_Cells/Option2_Catalogue/section-3-scale-microscopy/microscopy-comparison.svg",
    id: "biology-light-vs-electron-microscope",
    kind: "image",
    subject: "biology",
    topic_phrase: "light microscope versus electron microscope cell view comparison",
    keywords: ["light-microscope", "electron-microscope", "magnification", "comparison", "microscopy", "g6-cells"],
    source_unit: "G6-SCI-001",
  },

  // ── G6-ENG-002 Electronics Basics (issue #331) ─────────────────────────────
  // (subject="physics" since engineering is not in the closed SUBJECTS enum;
  //  electronics keyword + g6-electronics tag identify the unit)
  {
    asset: "sample_content/g6-stem/G6-ENG-002_Electronics_Basics/Option2_Catalogue/section-1-components/circuit-component-symbols.svg",
    id: "electronics-circuit-component-symbols-reference",
    kind: "image-grid",
    subject: "physics",
    topic_phrase: "circuit schematic component symbols wire resistor battery lamp switch capacitor led ground",
    keywords: ["schematic", "components", "symbols", "reference-card", "circuit", "g6-electronics"],
    source_unit: "G6-ENG-002",
  },
  {
    asset: "sample_content/g6-stem/G6-ENG-002_Electronics_Basics/Option2_Catalogue/section-1-components/resistor-anatomy.svg",
    id: "electronics-resistor-anatomy-and-symbol",
    kind: "image",
    subject: "physics",
    topic_phrase: "resistor real component colour bands ohms schematic zigzag symbol",
    keywords: ["resistor", "ohms", "colour-bands", "zigzag", "schematic", "g6-electronics"],
    source_unit: "G6-ENG-002",
  },
  {
    asset: "sample_content/g6-stem/G6-ENG-002_Electronics_Basics/Option2_Catalogue/section-1-components/capacitor-anatomy.svg",
    id: "electronics-capacitor-anatomy-and-symbol",
    kind: "image",
    subject: "physics",
    topic_phrase: "capacitor real component two plates schematic symbol farads",
    keywords: ["capacitor", "farads", "two-plates", "schematic", "g6-electronics"],
    source_unit: "G6-ENG-002",
  },
  {
    asset: "sample_content/g6-stem/G6-ENG-002_Electronics_Basics/Option2_Catalogue/section-1-components/battery-and-cell-anatomy.svg",
    id: "electronics-battery-single-vs-multi-cell",
    kind: "image",
    subject: "physics",
    topic_phrase: "battery single cell versus multi cell series voltage schematic symbol",
    keywords: ["battery", "cell", "voltage", "series", "schematic", "g6-electronics"],
    source_unit: "G6-ENG-002",
  },
  {
    asset: "sample_content/g6-stem/G6-ENG-002_Electronics_Basics/Option2_Catalogue/section-2-circuits/simple-circuit-with-lamp.svg",
    id: "electronics-simple-circuit-battery-switch-lamp",
    kind: "image",
    subject: "physics",
    topic_phrase: "simple circuit battery switch lamp closed loop current",
    keywords: ["simple-circuit", "lamp", "battery", "switch", "loop", "g6-electronics"],
    source_unit: "G6-ENG-002",
  },
  {
    asset: "sample_content/g6-stem/G6-ENG-002_Electronics_Basics/Option2_Catalogue/section-2-circuits/series-circuit.svg",
    id: "electronics-series-circuit-two-lamps",
    kind: "image",
    subject: "physics",
    topic_phrase: "series circuit two lamps single loop same current voltage divides",
    keywords: ["series", "circuit", "two-lamps", "same-current", "voltage-divides", "g6-electronics"],
    source_unit: "G6-ENG-002",
  },
  {
    asset: "sample_content/g6-stem/G6-ENG-002_Electronics_Basics/Option2_Catalogue/section-2-circuits/parallel-circuit.svg",
    id: "electronics-parallel-circuit-two-lamps",
    kind: "image",
    subject: "physics",
    topic_phrase: "parallel circuit two lamp branches same voltage current splits",
    keywords: ["parallel", "circuit", "branches", "same-voltage", "current-splits", "g6-electronics"],
    source_unit: "G6-ENG-002",
  },
  {
    asset: "sample_content/g6-stem/G6-ENG-002_Electronics_Basics/Option2_Catalogue/section-2-circuits/series-vs-parallel-comparison.svg",
    id: "electronics-series-vs-parallel-broken-bulb",
    kind: "image-grid",
    subject: "physics",
    topic_phrase: "series versus parallel circuit when one lamp breaks side by side",
    keywords: ["series", "parallel", "comparison", "broken-bulb", "side-by-side", "g6-electronics"],
    source_unit: "G6-ENG-002",
  },
  {
    asset: "sample_content/g6-stem/G6-ENG-002_Electronics_Basics/Option2_Catalogue/section-2-circuits/led-with-current-limit-resistor.svg",
    id: "electronics-led-with-current-limit-resistor",
    kind: "image",
    subject: "physics",
    topic_phrase: "led with current limit resistor protection circuit",
    keywords: ["led", "current-limit", "resistor", "protection", "circuit", "g6-electronics"],
    source_unit: "G6-ENG-002",
  },
  {
    asset: "sample_content/g6-stem/G6-ENG-002_Electronics_Basics/Option2_Catalogue/section-3-flow-and-laws/current-flow-direction.svg",
    id: "electronics-conventional-current-vs-electron-flow",
    kind: "image",
    subject: "physics",
    topic_phrase: "conventional current versus electron flow direction opposite",
    keywords: ["conventional-current", "electron-flow", "direction", "convention", "circuit", "g6-electronics"],
    source_unit: "G6-ENG-002",
  },
  {
    asset: "sample_content/g6-stem/G6-ENG-002_Electronics_Basics/Option2_Catalogue/section-3-flow-and-laws/open-vs-closed-circuit.svg",
    id: "electronics-open-vs-closed-circuit",
    kind: "image-grid",
    subject: "physics",
    topic_phrase: "open versus closed switch circuit current flow comparison",
    keywords: ["open-circuit", "closed-circuit", "switch", "comparison", "g6-electronics"],
    source_unit: "G6-ENG-002",
  },
  {
    asset: "sample_content/g6-stem/G6-ENG-002_Electronics_Basics/Option2_Catalogue/section-3-flow-and-laws/ohms-law-relationship.svg",
    id: "electronics-ohms-law-triangle",
    kind: "image",
    subject: "physics",
    topic_phrase: "ohms law triangle voltage current resistance v equals i r",
    keywords: ["ohms-law", "triangle", "voltage", "current", "resistance", "g6-electronics"],
    source_unit: "G6-ENG-002",
  },
  {
    asset: "sample_content/g6-stem/G6-ENG-002_Electronics_Basics/Option2_Catalogue/section-3-flow-and-laws/short-circuit-warning.svg",
    id: "electronics-short-circuit-warning",
    kind: "image",
    subject: "physics",
    topic_phrase: "short circuit warning bypassing load battery overheat",
    keywords: ["short-circuit", "warning", "danger", "overload", "g6-electronics"],
    source_unit: "G6-ENG-002",
  },

  // ── G7-SCI-001 Atoms and Periodic Table (issue #332) ───────────────────────
  {
    asset: "sample_content/g7-stem/G7-SCI-001_Atoms_and_Periodic_Table/Option2_Catalogue/section-1-atoms/periodic-table-overview.svg",
    id: "chemistry-periodic-table-overview-g7",
    kind: "image",
    subject: "chemistry",
    topic_phrase: "periodic table overview periods groups categories coloured",
    keywords: ["periodic-table", "overview", "groups", "categories", "g7-atoms"],
    source_unit: "G7-SCI-001",
  },
  {
    asset: "sample_content/g7-stem/G7-SCI-001_Atoms_and_Periodic_Table/Option2_Catalogue/section-1-atoms/element-card-anatomy.svg",
    id: "chemistry-element-card-anatomy",
    kind: "image",
    subject: "chemistry",
    topic_phrase: "periodic table element tile atomic number symbol name mass anatomy",
    keywords: ["element-tile", "atomic-number", "symbol", "atomic-mass", "anatomy", "g7-atoms"],
    source_unit: "G7-SCI-001",
  },
  {
    asset: "sample_content/g7-stem/G7-SCI-001_Atoms_and_Periodic_Table/Option2_Catalogue/section-1-atoms/bohr-shells-first-twenty.svg",
    id: "chemistry-bohr-shells-first-twenty-elements",
    kind: "image-grid",
    subject: "chemistry",
    topic_phrase: "bohr shells first twenty elements hydrogen calcium periodic layout",
    keywords: ["bohr-shells", "first-twenty", "hydrogen-to-calcium", "periodic-layout", "g7-atoms"],
    source_unit: "G7-SCI-001",
  },
  {
    asset: "sample_content/g7-stem/G7-SCI-001_Atoms_and_Periodic_Table/Option2_Catalogue/section-1-atoms/group-vs-period-highlight.svg",
    id: "chemistry-group-vs-period-highlight",
    kind: "image",
    subject: "chemistry",
    topic_phrase: "periodic table group versus period column row highlighting",
    keywords: ["group", "period", "column", "row", "alkali-metals", "g7-atoms"],
    source_unit: "G7-SCI-001",
  },
  {
    asset: "sample_content/g7-stem/G7-SCI-001_Atoms_and_Periodic_Table/Option2_Catalogue/section-1-atoms/metal-nonmetal-metalloid-zones.svg",
    id: "chemistry-metal-nonmetal-metalloid-zones",
    kind: "image",
    subject: "chemistry",
    topic_phrase: "periodic table metal nonmetal metalloid staircase zones",
    keywords: ["metal", "nonmetal", "metalloid", "staircase", "zones", "g7-atoms"],
    source_unit: "G7-SCI-001",
  },
  {
    asset: "sample_content/g7-stem/G7-SCI-001_Atoms_and_Periodic_Table/Option2_Catalogue/section-2-trends/atomic-radius-heatmap.svg",
    id: "chemistry-atomic-radius-periodic-trend-heatmap",
    kind: "image",
    subject: "chemistry",
    topic_phrase: "atomic radius periodic trend heatmap colour coded",
    keywords: ["atomic-radius", "heatmap", "periodic-trend", "size", "g7-atoms"],
    source_unit: "G7-SCI-001",
  },
  {
    asset: "sample_content/g7-stem/G7-SCI-001_Atoms_and_Periodic_Table/Option2_Catalogue/section-2-trends/ionization-energy-heatmap.svg",
    id: "chemistry-ionization-energy-periodic-trend-heatmap",
    kind: "image",
    subject: "chemistry",
    topic_phrase: "ionization energy first periodic trend heatmap colour coded",
    keywords: ["ionization-energy", "heatmap", "periodic-trend", "first-ie", "g7-atoms"],
    source_unit: "G7-SCI-001",
  },
  {
    asset: "sample_content/g7-stem/G7-SCI-001_Atoms_and_Periodic_Table/Option2_Catalogue/section-2-trends/electronegativity-heatmap.svg",
    id: "chemistry-electronegativity-periodic-trend-heatmap",
    kind: "image",
    subject: "chemistry",
    topic_phrase: "electronegativity pauling scale periodic trend heatmap",
    keywords: ["electronegativity", "pauling", "heatmap", "periodic-trend", "g7-atoms"],
    source_unit: "G7-SCI-001",
  },
  {
    asset: "sample_content/g7-stem/G7-SCI-001_Atoms_and_Periodic_Table/Option2_Catalogue/section-2-trends/trends-arrows-summary.svg",
    id: "chemistry-periodic-trends-arrows-summary",
    kind: "image",
    subject: "chemistry",
    topic_phrase: "periodic trends arrows summary direction radius ionization electronegativity",
    keywords: ["periodic-trends", "arrows", "summary", "direction", "all-trends", "g7-atoms"],
    source_unit: "G7-SCI-001",
  },

  // ── G10-SCI-004 Organic Chemistry (issue #333) ─────────────────────────────
  {
    asset: "sample_content/g10-stem/G10-SCI-004_Organic_Chemistry/Option2_Catalogue/section-1-skeletal-structures/skeletal-shorthand-rules.svg",
    id: "chemistry-organic-skeletal-shorthand-rules",
    kind: "image",
    subject: "chemistry",
    topic_phrase: "skeletal structure shorthand rules full condensed butane comparison",
    keywords: ["skeletal", "shorthand", "butane", "comparison", "g10-organic"],
    source_unit: "G10-SCI-004",
  },
  {
    asset: "sample_content/g10-stem/G10-SCI-004_Organic_Chemistry/Option2_Catalogue/section-1-skeletal-structures/alkane-series-zigzag.svg",
    id: "chemistry-organic-alkane-series-zigzag",
    kind: "image",
    subject: "chemistry",
    topic_phrase: "alkane homologous series methane to pentane zigzag",
    keywords: ["alkane", "series", "methane", "pentane", "zigzag", "g10-organic"],
    source_unit: "G10-SCI-004",
  },
  {
    asset: "sample_content/g10-stem/G10-SCI-004_Organic_Chemistry/Option2_Catalogue/section-1-skeletal-structures/branched-vs-straight-pentanes.svg",
    id: "chemistry-organic-pentane-isomers-branched",
    kind: "image",
    subject: "chemistry",
    topic_phrase: "pentane constitutional isomers straight branched neo boiling points",
    keywords: ["pentane", "isomers", "constitutional", "branched", "boiling-point", "g10-organic"],
    source_unit: "G10-SCI-004",
  },
  {
    asset: "sample_content/g10-stem/G10-SCI-004_Organic_Chemistry/Option2_Catalogue/section-1-skeletal-structures/cyclohexane-shapes.svg",
    id: "chemistry-organic-cyclohexane-hexagon-and-chair",
    kind: "image",
    subject: "chemistry",
    topic_phrase: "cyclohexane hexagon skeletal versus chair conformation",
    keywords: ["cyclohexane", "hexagon", "chair-conformation", "ring", "g10-organic"],
    source_unit: "G10-SCI-004",
  },
  {
    asset: "sample_content/g10-stem/G10-SCI-004_Organic_Chemistry/Option2_Catalogue/section-1-skeletal-structures/numbering-the-chain.svg",
    id: "chemistry-organic-chain-numbering-lowest-locants",
    kind: "image",
    subject: "chemistry",
    topic_phrase: "carbon chain numbering lowest locants iupac rule",
    keywords: ["chain-numbering", "locants", "iupac", "2-methylbutane", "g10-organic"],
    source_unit: "G10-SCI-004",
  },
  {
    asset: "sample_content/g10-stem/G10-SCI-004_Organic_Chemistry/Option2_Catalogue/section-2-multiple-bonds-aromatics/alkene-double-bond.svg",
    id: "chemistry-organic-alkene-double-bond",
    kind: "image",
    subject: "chemistry",
    topic_phrase: "alkene double bond ethene propene butene skeletal",
    keywords: ["alkene", "double-bond", "ethene", "propene", "g10-organic"],
    source_unit: "G10-SCI-004",
  },
  {
    asset: "sample_content/g10-stem/G10-SCI-004_Organic_Chemistry/Option2_Catalogue/section-2-multiple-bonds-aromatics/alkyne-triple-bond.svg",
    id: "chemistry-organic-alkyne-triple-bond",
    kind: "image",
    subject: "chemistry",
    topic_phrase: "alkyne triple bond ethyne acetylene propyne skeletal",
    keywords: ["alkyne", "triple-bond", "ethyne", "acetylene", "g10-organic"],
    source_unit: "G10-SCI-004",
  },
  {
    asset: "sample_content/g10-stem/G10-SCI-004_Organic_Chemistry/Option2_Catalogue/section-2-multiple-bonds-aromatics/cis-trans-isomerism.svg",
    id: "chemistry-organic-cis-trans-2-butene",
    kind: "image",
    subject: "chemistry",
    topic_phrase: "cis trans isomers 2-butene geometric same versus opposite sides",
    keywords: ["cis-trans", "geometric-isomer", "2-butene", "double-bond", "g10-organic"],
    source_unit: "G10-SCI-004",
  },
  {
    asset: "sample_content/g10-stem/G10-SCI-004_Organic_Chemistry/Option2_Catalogue/section-2-multiple-bonds-aromatics/benzene-resonance.svg",
    id: "chemistry-organic-benzene-resonance-and-circle",
    kind: "image",
    subject: "chemistry",
    topic_phrase: "benzene kekule resonance forms circle delocalised electrons",
    keywords: ["benzene", "kekule", "resonance", "aromatic", "delocalised", "g10-organic"],
    source_unit: "G10-SCI-004",
  },
  {
    asset: "sample_content/g10-stem/G10-SCI-004_Organic_Chemistry/Option2_Catalogue/section-3-functional-groups/functional-groups-reference.svg",
    id: "chemistry-organic-functional-groups-reference",
    kind: "image-grid",
    subject: "chemistry",
    topic_phrase: "functional groups reference alcohol aldehyde ketone acid ester amine halide",
    keywords: ["functional-groups", "reference", "alcohol", "carbonyl", "amine", "g10-organic"],
    source_unit: "G10-SCI-004",
  },
  {
    asset: "sample_content/g10-stem/G10-SCI-004_Organic_Chemistry/Option2_Catalogue/section-3-functional-groups/alcohol-aldehyde-ketone-card.svg",
    id: "chemistry-organic-alcohol-aldehyde-ketone",
    kind: "image",
    subject: "chemistry",
    topic_phrase: "alcohol aldehyde ketone three related carbonyl groups oxygen",
    keywords: ["alcohol", "aldehyde", "ketone", "carbonyl", "ethanol", "g10-organic"],
    source_unit: "G10-SCI-004",
  },
  {
    asset: "sample_content/g10-stem/G10-SCI-004_Organic_Chemistry/Option2_Catalogue/section-3-functional-groups/carboxylic-acid-and-ester-card.svg",
    id: "chemistry-organic-carboxylic-acid-and-ester",
    kind: "image",
    subject: "chemistry",
    topic_phrase: "carboxylic acid ester functional groups vinegar fruit",
    keywords: ["carboxylic-acid", "ester", "ethanoic-acid", "functional-group", "g10-organic"],
    source_unit: "G10-SCI-004",
  },
  {
    asset: "sample_content/g10-stem/G10-SCI-004_Organic_Chemistry/Option2_Catalogue/section-3-functional-groups/amine-and-amide-card.svg",
    id: "chemistry-organic-amine-and-amide",
    kind: "image",
    subject: "chemistry",
    topic_phrase: "amine amide nitrogen functional groups protein building block",
    keywords: ["amine", "amide", "nitrogen", "protein", "functional-group", "g10-organic"],
    source_unit: "G10-SCI-004",
  },
  {
    asset: "sample_content/g10-stem/G10-SCI-004_Organic_Chemistry/Option2_Catalogue/section-4-iupac-naming/iupac-naming-flowchart.svg",
    id: "chemistry-organic-iupac-naming-flowchart",
    kind: "image",
    subject: "chemistry",
    topic_phrase: "iupac naming five step flowchart parent chain substituents locants suffix",
    keywords: ["iupac", "naming", "flowchart", "five-steps", "g10-organic"],
    source_unit: "G10-SCI-004",
  },
  {
    asset: "sample_content/g10-stem/G10-SCI-004_Organic_Chemistry/Option2_Catalogue/section-4-iupac-naming/name-build-walkthrough.svg",
    id: "chemistry-organic-iupac-name-walkthrough",
    kind: "image",
    subject: "chemistry",
    topic_phrase: "iupac name build walkthrough 3-bromo-2-methylbutane example",
    keywords: ["iupac", "walkthrough", "naming", "worked-example", "g10-organic"],
    source_unit: "G10-SCI-004",
  },
  {
    asset: "sample_content/g10-stem/G10-SCI-004_Organic_Chemistry/Option2_Catalogue/section-4-iupac-naming/prefix-and-suffix-cheat-sheet.svg",
    id: "chemistry-organic-iupac-prefix-suffix-cheatsheet",
    kind: "image",
    subject: "chemistry",
    topic_phrase: "iupac naming prefixes suffixes cheat sheet meth eth prop oic ol",
    keywords: ["iupac", "prefixes", "suffixes", "cheat-sheet", "naming", "g10-organic"],
    source_unit: "G10-SCI-004",
  },

  // ── G11-MATH-002 Derivatives — Rules and Applications (issue #334) ─────────
  {
    asset: "sample_content/g11-stem/G11-MATH-002_Derivatives_Rules_and_Applications/Option2_Catalogue/section-1-derivative-concept/secant-and-tangent-lines.svg",
    id: "math-derivatives-secant-and-tangent-lines",
    kind: "image",
    subject: "math",
    topic_phrase: "secant line versus tangent line on curve calculus",
    keywords: ["secant", "tangent", "calculus", "derivative", "g11-derivatives"],
    source_unit: "G11-MATH-002",
  },
  {
    asset: "sample_content/g11-stem/G11-MATH-002_Derivatives_Rules_and_Applications/Option2_Catalogue/section-1-derivative-concept/tangent-as-limit-of-secants.svg",
    id: "math-derivatives-tangent-as-limit-of-secants",
    kind: "image",
    subject: "math",
    topic_phrase: "tangent line as limit of secants delta x to zero derivative definition",
    keywords: ["tangent", "limit", "secant", "delta-x", "derivative-definition", "g11-derivatives"],
    source_unit: "G11-MATH-002",
  },
  {
    asset: "sample_content/g11-stem/G11-MATH-002_Derivatives_Rules_and_Applications/Option2_Catalogue/section-1-derivative-concept/derivative-as-slope-along-curve.svg",
    id: "math-derivatives-as-slope-along-curve",
    kind: "image",
    subject: "math",
    topic_phrase: "derivative as slope along curve f and f prime stacked plots",
    keywords: ["derivative", "slope", "f-prime", "stacked-plots", "g11-derivatives"],
    source_unit: "G11-MATH-002",
  },
  {
    asset: "sample_content/g11-stem/G11-MATH-002_Derivatives_Rules_and_Applications/Option2_Catalogue/section-2-rules/power-rule-card.svg",
    id: "math-derivatives-power-rule",
    kind: "image",
    subject: "math",
    topic_phrase: "power rule differentiation x to the n bring down exponent",
    keywords: ["power-rule", "differentiation", "exponent", "g11-derivatives"],
    source_unit: "G11-MATH-002",
  },
  {
    asset: "sample_content/g11-stem/G11-MATH-002_Derivatives_Rules_and_Applications/Option2_Catalogue/section-2-rules/chain-rule-decomposition.svg",
    id: "math-derivatives-chain-rule-decomposition",
    kind: "image",
    subject: "math",
    topic_phrase: "chain rule decomposition outer inner composite function",
    keywords: ["chain-rule", "composite", "outer-inner", "differentiation", "g11-derivatives"],
    source_unit: "G11-MATH-002",
  },
  {
    asset: "sample_content/g11-stem/G11-MATH-002_Derivatives_Rules_and_Applications/Option2_Catalogue/section-2-rules/product-and-quotient-rules.svg",
    id: "math-derivatives-product-and-quotient-rules",
    kind: "image",
    subject: "math",
    topic_phrase: "product rule quotient rule differentiation u v formulas",
    keywords: ["product-rule", "quotient-rule", "differentiation", "g11-derivatives"],
    source_unit: "G11-MATH-002",
  },
  {
    asset: "sample_content/g11-stem/G11-MATH-002_Derivatives_Rules_and_Applications/Option2_Catalogue/section-3-applications/optimization-extrema.svg",
    id: "math-derivatives-optimization-local-extrema",
    kind: "image",
    subject: "math",
    topic_phrase: "local extrema maxima minima where f prime equals zero horizontal tangent",
    keywords: ["optimization", "extrema", "maximum", "minimum", "critical-point", "g11-derivatives"],
    source_unit: "G11-MATH-002",
  },
  {
    asset: "sample_content/g11-stem/G11-MATH-002_Derivatives_Rules_and_Applications/Option2_Catalogue/section-3-applications/related-rates-balloon.svg",
    id: "math-derivatives-related-rates-balloon",
    kind: "image",
    subject: "math",
    topic_phrase: "related rates balloon inflating volume radius dV dt dr dt",
    keywords: ["related-rates", "balloon", "implicit-differentiation", "volume", "g11-derivatives"],
    source_unit: "G11-MATH-002",
  },
  {
    asset: "sample_content/g11-stem/G11-MATH-002_Derivatives_Rules_and_Applications/Option2_Catalogue/section-3-applications/motion-position-velocity-acceleration.svg",
    id: "math-derivatives-position-velocity-acceleration",
    kind: "image-grid",
    subject: "math",
    topic_phrase: "position velocity acceleration successive derivatives stacked plots",
    keywords: ["position", "velocity", "acceleration", "successive-derivatives", "stacked", "g11-derivatives"],
    source_unit: "G11-MATH-002",
  },
];


function emit(spec: SidecarSpec): string {
  const keywordLines = spec.keywords.map((k) => `  - ${k}`).join("\n");
  return `# Auto-generated by scripts/seed_library_sidecars.ts — edit the spec there
# and re-run: bun scripts/seed_library_sidecars.ts
schema_version: 1
id: ${spec.id}
kind: ${spec.kind}
subject: ${spec.subject}
topic_phrase: "${spec.topic_phrase}"
keywords:
${keywordLines}
license: platform-cc-by-sa
source_unit: ${spec.source_unit}
`;
}


function sidecarPath(assetPath: string): string {
  // Replace the asset extension with .metadata.yaml
  const dot = assetPath.lastIndexOf(".");
  return assetPath.slice(0, dot) + ".metadata.yaml";
}


let written = 0;
for (const spec of SPECS) {
  const sidecar = sidecarPath(spec.asset);
  const path = join(REPO_ROOT, sidecar);
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, emit(spec));
  written++;
}

console.log(`wrote ${written} sidecar(s)`);
